name: Build Majin Slides

on:
  workflow_dispatch:
    inputs:
      md_path:
        description: "Markdown path to render"
        required: true
        default: "slides/sample.md"
      title:
        description: "Presentation title"
        required: false
        default: "Majin Slides"
      folder_id:
        description: "Google Drive Folder ID (optional)"
        required: false
        default: ""
      share_email:
        description: "Share with this email (writer) (optional)"
        required: false
        default: ""
  push:
    paths:
      - "**/*.md"
      - "slides/themes/**"
      - ".github/workflows/slides.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install fonts (optional but recommended)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-noto-color-emoji

      - name: Install deps (marp-cli + googleapis)
        run: |
          npm -v
          npm i -D @marp-team/marp-cli@latest
          npm i googleapis@latest

      - name: Render slides via Marp
        env:
          MD_PATH: ${{ github.event.inputs.md_path }}
          TITLE: ${{ github.event.inputs.title }}
        run: |
          set -euxo pipefail
          MD=${MD_PATH:-}
          if [ -z "$MD" ]; then MD="slides/sample.md"; fi
          T=${TITLE:-"Majin Slides"}
          echo "Using MD_PATH=$MD\nUsing TITLE=$T"
          test -f "$MD" || (echo "Markdown not found: $MD"; git ls-files; exit 1)
          ls -la slides/themes || true
          mkdir -p dist
          npx marp --version
          # PDF / PPTX / HTML
          npx marp "$MD" --theme-set slides/themes/majin.css --allow-local-files --pdf --output dist/slides.pdf
          npx marp "$MD" --theme-set slides/themes/majin.css --allow-local-files --pptx --output dist/slides.pptx
          npx marp "$MD" --theme-set slides/themes/majin.css --allow-local-files --html --output dist/slides.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: majin-slides
          path: dist/

      - name: Upload PPTX to Google Slides (convert)
        id: upload
        if: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON != '' }}
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GDRIVE_FOLDER_ID: ${{ github.event.inputs.folder_id }}
          GDRIVE_SHARE_EMAIL: ${{ github.event.inputs.share_email }}
          TITLE: ${{ github.event.inputs.title }}
        run: |
          T=${TITLE:-"Majin Slides"}
          node ./scripts/upload-to-gslides.mjs ./dist/slides.pptx "$T"

      - name: Summary
        run: |
          if [ -f .gslides-url ]; then
            echo "Slides URL: $(cat .gslides-url)" >> $GITHUB_STEP_SUMMARY
          else
            echo "Google Slides conversion skipped (no secret)." >> $GITHUB_STEP_SUMMARY
          fi
